const restaurant = {
    name: 'FreshFood',
    description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Id, rem. Culpa fuga, ab harum dicta inventore nulla vero exercitationem perspiciatis consequatur voluptatum tempore sunt similique, illo aliquam est doloremque molestias.',
    minimumOrderValue: 10,
    deliveryPrice: 1,
    categories: [
        {name: 'Beliebte Gerichte', description: '', image: ''},
        {name: 'Salate', description: 'Alle Salate werden mit einem Dressing nach Wahl zubereitet.', image: 'res/salad-category-header.jpg'},
        {name: 'Wraps', description: '', image: 'res/wraps-category-header.jpg'},
        {name: 'Wrap Teller', description: '', image: 'res/wrap-plate-category-header.jpg'},
        {name: 'Beilagen', description: '', image: 'res/side-dishes-category-header.jpg'},
        {name: 'Alkoholfreie Getränke', description: '', image: 'res/drinks-category-header.jpg'},
    ],
    products: [
        {name: 'Orient Teller', category: 'Beliebte Gerichte', description: 'mit Falafel, hausgemachtem Hummus und Couscous', price: 8.5},
        {name: 'FreshFood Wrap Menü', category: 'Beliebte Gerichte', description: '<ul><li>1 Siba Wrap<li>Couscous<li>griechischer Joghurt mit Olivenöl</ul>', price: 7.5},
        {name: 'FreshFood Wrap', category: 'Beliebte Gerichte', description: 'mit Putenbrust, Rucola, rotem Eichblattsalat, Krautsalat, Gemüsezwiebeln und Tomaten', price: 5.7},
        {name: 'Gemischter Salat', category: 'Salate', description: 'mit Karotten, Tomaten, Zwiebeln, Krautsalat, rotem Eichblattsalat, Mais, Eisbergsalat, Bankett-Salat und Gurken', price: 6.5},
        {name: 'FreshFood Salat', category: 'Salate', description: 'mit rotem Eichblattsalat, Krautsalat, Tomaten, Bankettsalat, Granatapfelkernen, Orangensaft, Granatapfel und Orange', price: 7.5},
        {name: 'Vegetarischer Wrap', category: 'Wraps', description: 'mit Avocado', price: 5.7},
        {name: 'FreshFood Wrap', category: 'Wraps', description: 'mit Putenbrust, Rucola, rotem Eichblattsalat, Krautsalat, Gemüsezwiebeln und Tomaten', price: 5.7},
        {name: 'Beef Wrap', category: 'Wraps', description: 'mit Hüftsteak und Babyspinat', price: 6.9},
        {name: 'Safran Wrap', category: 'Wraps', description: 'mit Safranhähnchen, gemischtem Salat und gedünsteten Zwiebeln', price: 7.5},
        {name: 'Orient Wrap', category: 'Wraps', description: 'mit selbstgemachtem Hummus, Falafel und gemischtem Salat', price: 6.9},
        {name: 'Vegetarischer Teller', category: 'Wrap Teller', description: 'mit Avocado', price: 7.9},
        {name: 'FreshFood Teller', category: 'Wrap Teller', description: 'mit Putenbrust, Rucola, rotem Eichblattsalat, Krautsalat, Gemüsezwiebeln und Tomaten', price: 7.9},
        {name: 'Beef Teller', category: 'Wrap Teller', description: 'mit Hüftsteak und Babyspinat', price: 9},
        {name: 'Safran Teller', category: 'Wrap Teller', description: 'mit Safranhähnchen, gemischtem Salat und gedünsteten Zwiebeln', price: 9.5},
        {name: 'Orient Teller', category: 'Wrap Teller', description: 'mit selbstgemachtem Hummus, Falafel und gemischtem Salat', price: 8.5},
        {name: 'Belgische Pommes Frites', category: 'Beilagen', description: '', price: 2.9},
        {name: 'Süßkartoffel-Pommes', category: 'Beilagen', description: '', price: 3.9},
        {name: 'Hausgemachte Sauce', category: 'Beilagen', description: '', price: 0.7},
        {name: 'Orangensaft 0.4l', category: 'Alkoholfreie Getränke', description: '', price: 3.5},
        {name: 'Granatapfelsaft 0.3l', category: 'Alkoholfreie Getränke', description: '', price: 3.9},
        {name: 'Capri Sun 0.2l', category: 'Alkoholfreie Getränke', description: '', price: 1},
    ]
}